### ISSUE TITLE
Add new Drush command az-core-config-add-permissions

### ISSUE THREAD

**Issue by slaymoore** [uazgraduatecollege/pantheon-tools#10]
There is a [new](https://github.com/az-digital/az_quickstart/pull/2208) Drush command as part of AZ Quickstart that adds missing permissions from the installation profile. Campus Web Services added it to their Pantheon scripts immediately after applying config distro updates.

`terminus drush ${SITE_NAME}.test -- -n -y az-core-config-add-permissions`

**Comment by pbarabe** [comment]
@jwmoore1 tyvm! I'll add that to our scripts.
